version: "3.9"

services:
  redis:
    image: redis:7.0.8-alpine
  app:
    depends_on:
      - redis
    build: 
      dockerfile: Dockerfile
      context: .
    environment:
      REDIS_ADDRESS: redis:6379
      TEST_REDIS_ADDRESS: redis:6379
    ports:
      - "8080:8080"